import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'
import Footer from '@/components/footer'
import CustomProvider from "@/redux/CartProvider";
import store from "@/redux/store"
import AuthProvider from '@/components/authProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
       <CustomProvider><AuthProvider> <Navbar></Navbar>{children}</AuthProvider></CustomProvider><Footer></Footer></body>
    </html>
  );
}
